---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: digital-twin-api-dev
  namespace: stg
  annotations:
#    flux.weave.works/automated: "true"
#    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: digital-twin-api-dev-rn
  chart:
    git: git@bitbucket.org:iminds/digital-twin-k8s
    path: digital-twin/charts/backend/charts/api
    ref: feature/DIG-723_flux
  values:
    image:
      tag: 0.5.2
    imagePullSecrets:
      - name: digitaltwinregistry
    ingress:
      enabled: true
      tls: []
      hosts:
        - host: api.minikube.local
          paths:
            - /(.*)
    environment:
      PROTOCOL: http
