---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: digital-twin
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: digital-twin
  chart:
    git: git@bitbucket.org:iminds/digital-twin-k8s
    path: digital-twin
    ref: feature/DIG-723_flux
  values:
    frontend:
      image:
        registry: digitaltwincontainerregistry.azurecr.io
        repository: digital-twin-web-frontend
        tag: 0.5.0-alpha.72

    backend:
      api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-api
          tag: 0.5.2

      maps-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-maps-api
          tag: 0.4.1

      config-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-config-api
          tag: 0.1.0

      tag-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-tag-api
          tag: 0.1.1

      data-layer-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-data-layer-api
          tag: 0.1.0

      legends-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-legends-api
          tag: 0.1.1

      visualisation-api:
        image:
          registry: digitaltwincontainerregistry.azurecr.io
          repository: digital-twin-visualisation-api
          tag: 0.1.0

  valuesFrom:
  - chartFileRef:
      path: environments/local/config.yaml
  - chartFileRef:
      path: environments/local/environment.yaml
